name: Deploy to AWS Lightsail

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  LIGHTSAIL_INSTANCE: Ubuntu-1
  LIGHTSAIL_IP: 54.218.190.225

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests
          ls -la target/  # List contents of target directory for debugging

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/lightsail_key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/ /\n/g' >> ~/.ssh/lightsail_key
          echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/lightsail_key
          chmod 600 ~/.ssh/lightsail_key
          ssh-keyscan -H ${{ env.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts
          
          # Test SSH connection
          ssh -i ~/.ssh/lightsail_key -o StrictHostKeyChecking=no ubuntu@${{ env.LIGHTSAIL_IP }} 'echo "SSH connection successful"'

      - name: Copy files to Lightsail
        run: |
          # Create deployment script
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          sudo apt-get update
          sudo apt install -y openjdk-17-jdk
          sudo mkdir -p /home/ubuntu/app
          sudo cp courses-0.0.1-SNAPSHOT.jar /home/ubuntu/app/
          sudo cp mcp-service.service /etc/systemd/system/
          sudo chown -R ubuntu:ubuntu /home/ubuntu/app
          sudo systemctl daemon-reload
          sudo systemctl enable mcp-service
          sudo systemctl restart mcp-service
          EOL

          # Make script executable
          chmod +x deploy.sh

          # List files to be copied for debugging
          echo "Files to be copied:"
          ls -la target/*.jar
          ls -la mcp-service.service
          ls -la deploy.sh

          # Copy files to Lightsail
          scp -i ~/.ssh/lightsail_key \
            target/courses-0.0.1-SNAPSHOT.jar \
            mcp-service.service \
            deploy.sh \
            ubuntu@${{ env.LIGHTSAIL_IP }}:~/

          # Execute deployment script
          ssh -i ~/.ssh/lightsail_key \
            ubuntu@${{ env.LIGHTSAIL_IP }} 'bash ~/deploy.sh' 